// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQL_Server.Data;

#nullable disable

namespace SQL_Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241102122607_Final")]
    partial class Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SQL_Server.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Province] + ', ' + [Canton] + ', ' + [District]", true);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Name] + ' ' + [FirstSurname] + ' ' + [SecondSurname]", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("SQL_Server.Models.AdminPhone", b =>
                {
                    b.Property<int>("Admin_id")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Admin_id", "Phone");

                    b.ToTable("AdminPhone");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessAssociate", b =>
                {
                    b.Property<int>("Legal_Id")
                        .HasColumnType("int");

                    b.Property<string>("BusinessManager_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessType_Identification")
                        .HasColumnType("int");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Province] + ', ' + [Canton] + ', ' + [District]", true);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SINPE")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Legal_Id");

                    b.HasIndex("BusinessManager_Email")
                        .IsUnique();

                    b.HasIndex("BusinessType_Identification");

                    b.ToTable("BusinessAssociate");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessAssociatePhone", b =>
                {
                    b.Property<int>("BusinessAssociate_Legal_Id")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("BusinessAssociate_Legal_Id", "Phone");

                    b.ToTable("BusinessAssociatePhone");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessManager", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Province] + ', ' + [Canton] + ', ' + [District]", true);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Name] + ' ' + [FirstSurname] + ' ' + [SecondSurname]", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Email");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BusinessManager");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessManagerPhone", b =>
                {
                    b.Property<string>("BusinessManager_Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("BusinessManager_Email", "Phone");

                    b.ToTable("BusinessManagerPhone");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessType", b =>
                {
                    b.Property<int?>("Identification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Identification"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Identification");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BusinessType");
                });

            modelBuilder.Entity("SQL_Server.Models.Cart", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<int?>("BusinessAssociate_Legal_Id")
                        .HasColumnType("int");

                    b.Property<int>("Client_Id")
                        .HasColumnType("int");

                    b.Property<int?>("TotalProductsPrice")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("Client_Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("SQL_Server.Models.Cart_Product", b =>
                {
                    b.Property<int>("Cart_Code")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Product_Code")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("Cart_Code", "Product_Code");

                    b.HasIndex("Product_Code");

                    b.ToTable("Cart_Product");
                });

            modelBuilder.Entity("SQL_Server.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Province] + ', ' + [Canton] + ', ' + [District]", true);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Name] + ' ' + [FirstSurname] + ' ' + [SecondSurname]", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Client");
                });

            modelBuilder.Entity("SQL_Server.Models.ConsolidatedSalesReportView", b =>
                {
                    b.Property<string>("Affiliate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conductor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Purchases")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceAmount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAmount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ConsolidatedSalesReport", (string)null);
                });

            modelBuilder.Entity("SQL_Server.Models.FeedBack", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("BusinessAssociate_Legal_Id")
                        .HasColumnType("int");

                    b.Property<double>("BusinessGrade")
                        .HasColumnType("float");

                    b.Property<double>("DeliveryManGrade")
                        .HasColumnType("float");

                    b.Property<string>("FeedBack_Business")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBack_DeliveryMan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBack_Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodDeliveryMan_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("OrderGrade")
                        .HasColumnType("float");

                    b.Property<int>("Order_Code")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAssociate_Legal_Id");

                    b.HasIndex("FoodDeliveryMan_UserId");

                    b.HasIndex("Order_Code")
                        .IsUnique();

                    b.ToTable("FeedBack");
                });

            modelBuilder.Entity("SQL_Server.Models.FoodDeliveryMan", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Province] + ', ' + [Canton] + ', ' + [District]", true);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Name] + ' ' + [FirstSurname] + ' ' + [SecondSurname]", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("FoodDeliveryMan");
                });

            modelBuilder.Entity("SQL_Server.Models.FoodDeliveryManPhone", b =>
                {
                    b.Property<string>("FoodDeliveryMan_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("FoodDeliveryMan_UserId", "Phone");

                    b.ToTable("FoodDeliveryManPhone");
                });

            modelBuilder.Entity("SQL_Server.Models.Order", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<int>("Client_Id")
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodDeliveryMan_UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalService")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("Client_Id");

                    b.HasIndex("FoodDeliveryMan_UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SQL_Server.Models.Order_Product", b =>
                {
                    b.Property<int>("Order_Code")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Product_Code")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("Order_Code", "Product_Code");

                    b.HasIndex("Product_Code");

                    b.ToTable("Order_Product");
                });

            modelBuilder.Entity("SQL_Server.Models.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<int>("BusinessAssociate_Legal_Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("BusinessAssociate_Legal_Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SQL_Server.Models.ProductPhoto", b =>
                {
                    b.Property<int>("Product_Code")
                        .HasColumnType("int");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Product_Code", "PhotoURL");

                    b.ToTable("ProductPhoto");
                });

            modelBuilder.Entity("SQL_Server.Models.ProofOfPayment", b =>
                {
                    b.Property<int?>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Code"));

                    b.Property<string>("ClientFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientPhone")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastDigitsCreditCard")
                        .HasColumnType("int");

                    b.Property<int>("Order_Code")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalPayment")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("Order_Code")
                        .IsUnique();

                    b.ToTable("ProofOfPayment");
                });

            modelBuilder.Entity("SQL_Server.Models.SalesReportByAffiliateView", b =>
                {
                    b.Property<string>("Affiliate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Purchases")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceAmount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAmount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_SalesReportByAffiliate", (string)null);
                });

            modelBuilder.Entity("SQL_Server.Models.TopSellingProductsView", b =>
                {
                    b.Property<string>("Affiliate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalRevenue")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSold")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_TopSellingProducts", (string)null);
                });

            modelBuilder.Entity("SQL_Server.Models.AdminPhone", b =>
                {
                    b.HasOne("SQL_Server.Models.Admin", "Admin")
                        .WithMany("AdminPhones")
                        .HasForeignKey("Admin_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessAssociate", b =>
                {
                    b.HasOne("SQL_Server.Models.BusinessManager", "BusinessManager")
                        .WithOne("BusinessAssociate")
                        .HasForeignKey("SQL_Server.Models.BusinessAssociate", "BusinessManager_Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQL_Server.Models.BusinessType", "BusinessType")
                        .WithMany("BusinessAssociates")
                        .HasForeignKey("BusinessType_Identification")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessManager");

                    b.Navigation("BusinessType");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessAssociatePhone", b =>
                {
                    b.HasOne("SQL_Server.Models.BusinessAssociate", "BusinessAssociate")
                        .WithMany("BusinessAssociatePhones")
                        .HasForeignKey("BusinessAssociate_Legal_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAssociate");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessManagerPhone", b =>
                {
                    b.HasOne("SQL_Server.Models.BusinessManager", "BusinessManager")
                        .WithMany("BusinessManagerPhones")
                        .HasForeignKey("BusinessManager_Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessManager");
                });

            modelBuilder.Entity("SQL_Server.Models.Cart", b =>
                {
                    b.HasOne("SQL_Server.Models.Client", "Client")
                        .WithMany("Carts")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SQL_Server.Models.Cart_Product", b =>
                {
                    b.HasOne("SQL_Server.Models.Cart", "Cart")
                        .WithMany("Cart_Products")
                        .HasForeignKey("Cart_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQL_Server.Models.Product", "Product")
                        .WithMany("Cart_Products")
                        .HasForeignKey("Product_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SQL_Server.Models.FeedBack", b =>
                {
                    b.HasOne("SQL_Server.Models.BusinessAssociate", "BusinessAssociate")
                        .WithMany("FeedBacks")
                        .HasForeignKey("BusinessAssociate_Legal_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SQL_Server.Models.FoodDeliveryMan", "FoodDeliveryMan")
                        .WithMany("FeedBacks")
                        .HasForeignKey("FoodDeliveryMan_UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SQL_Server.Models.Order", "Order")
                        .WithOne("FeedBack")
                        .HasForeignKey("SQL_Server.Models.FeedBack", "Order_Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessAssociate");

                    b.Navigation("FoodDeliveryMan");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SQL_Server.Models.FoodDeliveryManPhone", b =>
                {
                    b.HasOne("SQL_Server.Models.FoodDeliveryMan", "FoodDeliveryMan")
                        .WithMany("FoodDeliveryManPhones")
                        .HasForeignKey("FoodDeliveryMan_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodDeliveryMan");
                });

            modelBuilder.Entity("SQL_Server.Models.Order", b =>
                {
                    b.HasOne("SQL_Server.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQL_Server.Models.FoodDeliveryMan", "FoodDeliveryMan")
                        .WithMany("Orders")
                        .HasForeignKey("FoodDeliveryMan_UserId");

                    b.Navigation("Client");

                    b.Navigation("FoodDeliveryMan");
                });

            modelBuilder.Entity("SQL_Server.Models.Order_Product", b =>
                {
                    b.HasOne("SQL_Server.Models.Order", "Order")
                        .WithMany("Order_Products")
                        .HasForeignKey("Order_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQL_Server.Models.Product", "Product")
                        .WithMany("Order_Products")
                        .HasForeignKey("Product_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SQL_Server.Models.Product", b =>
                {
                    b.HasOne("SQL_Server.Models.BusinessAssociate", "BusinessAssociate")
                        .WithMany("Products")
                        .HasForeignKey("BusinessAssociate_Legal_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAssociate");
                });

            modelBuilder.Entity("SQL_Server.Models.ProductPhoto", b =>
                {
                    b.HasOne("SQL_Server.Models.Product", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("Product_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SQL_Server.Models.ProofOfPayment", b =>
                {
                    b.HasOne("SQL_Server.Models.Order", "Order")
                        .WithOne("ProofOfPayment")
                        .HasForeignKey("SQL_Server.Models.ProofOfPayment", "Order_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SQL_Server.Models.Admin", b =>
                {
                    b.Navigation("AdminPhones");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessAssociate", b =>
                {
                    b.Navigation("BusinessAssociatePhones");

                    b.Navigation("FeedBacks");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessManager", b =>
                {
                    b.Navigation("BusinessAssociate");

                    b.Navigation("BusinessManagerPhones");
                });

            modelBuilder.Entity("SQL_Server.Models.BusinessType", b =>
                {
                    b.Navigation("BusinessAssociates");
                });

            modelBuilder.Entity("SQL_Server.Models.Cart", b =>
                {
                    b.Navigation("Cart_Products");
                });

            modelBuilder.Entity("SQL_Server.Models.Client", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SQL_Server.Models.FoodDeliveryMan", b =>
                {
                    b.Navigation("FeedBacks");

                    b.Navigation("FoodDeliveryManPhones");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SQL_Server.Models.Order", b =>
                {
                    b.Navigation("FeedBack");

                    b.Navigation("Order_Products");

                    b.Navigation("ProofOfPayment");
                });

            modelBuilder.Entity("SQL_Server.Models.Product", b =>
                {
                    b.Navigation("Cart_Products");

                    b.Navigation("Order_Products");

                    b.Navigation("ProductPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
